# An example config file for gladsync.
# Default values are used if no value is provided.

# The URL to your GitLab instance. 
# Defaults to "https://gitlab.com"
gl_url: ''

# The personal access token to use when accessing GitLab
# REQUIRED
gl_pat: ''

# The ID of the group to create all new synced groups under
# The GitLab API disallows creation of top-level groups
# REQUIRED
gl_root: ''

# The URL to your Active Directory instance
# REQUIRED
ad_url: ''

# The distinguished name to use when accessing Active Directory
# REQUIRED
ad_user: ''

# The password to use when accessing Active Directory.
# REQUIRED
ad_pass: ''

# The base dn to be used for LDAP searches.
# Defaults to 'OU=Project Groups,OU=Groups,DC=ad,DC=iti,DC=lab'
ldap_base: ''

# a semicolon (;) separated list dn's of the groups to sync.
# Defaults to all groups within base.
ldap_sync_groups: ''

# The access level to give to each person added to a GitLab group
# Must be one of: [GUEST, REPORTER, DEVELOPER, MAINTAINER, OWNER]
# Defaults to DEVELOPER
access_level: ''

# The log file to write to.
# If no path is given, print to stdout.
log_file: ''
